---
- name: Install Transmit via Mac App Store
  command: mas install "{{ item.id }}"
  args:
    creates: /Applications/{{ item.name }}.app
  with_items:
    - { id: 403388562, name: "Transmit" }
  when: ansible_os_family == "Darwin" and prefer_mas_over_homebrew == true

- name: Install Transmit via Homebrew
  homebrew_cask:
    name: transmit
  when: ansible_os_family == "Darwin" and prefer_mas_over_homebrew == false
